spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/
      add: mappings=true
  redis:
    port: 6379
  jpa:
    show_sql: true
server:
  port: 8060

