spring:
  profiles:
    include: oauth
    active: local
  mvc:
   # static-path-pattern: /static/**
  redis:
    port: 6379
  jpa:
    show_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
server:
  port: 8060

datasource:
  url: jdbc:h2:mem:testdb




