spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mariadb://freelec-board-12.cerng6shgt9g.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: reason9347
    driver-class-name: org.mariadb.jdbc.Driver
