spring:
  profiles:
    include: oauth
    active: local
  mvc:
   # static-path-pattern: /static/**
  redis:
    port: 6379
  jpa:
    show_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
server:
  port: 8080

  datasource:
    url: jdbc:mariadb://freelec-board-12.cerng6shgt9g.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: reason9347
    driver-class-name: org.mariadb.jdbc.Driver




